# .devcontainer/Dockerfile

# Verwende ein Node-Image, das zu deiner Node.js-Version passt (z.B. 16)
FROM node:16

# Erstelle ein Arbeitsverzeichnis im Container
WORKDIR /workspace

# Benutzerrechte setzen
RUN chown -R node:node /workspace

# Benutzer wechseln
USER node
